class User{
    constructor(name, surname, type, username, password) {
        this.id //autogenerated(?)
        this.name = name;
        this.surname = surname;
        this.type = type;
        this.username = username;
        this.password = password;
    }

    setName(name) {
        this.name = name;
        return;
    }

    setSurname(surname) {
        this.surname = surname;
        return;
    }

    setUsername(username) {
        this.username = username;
        return;
    }

    setPassword(password) {
        this.password = password;
        return;
    }

    setType(type) {
        this.type = type;
        return;
    }

}

module.exports = User;